# Generated by Django 6.0.3 on 2026-03-11 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('investment_fund', 'Investment Fund'), ('pension_fund', 'Pension Fund'), ('crypto', 'Crypto'), ('bank_deposit', 'Bank Deposit')], max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('requires_manual_tracking', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Annual interest rate as a percentage e.g. 4.5000', max_digits=7, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='My Portfolio', max_length=100)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Cash Deposit'), ('withdraw', 'Cash Withdrawal')], max_length=10)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('from_budget', models.BooleanField(default=False)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invest.portfolio')),
                ('security', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invest.security')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('manual_current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='invest.portfolio')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holdings', to='invest.security')),
            ],
            options={
                'unique_together': {('portfolio', 'security')},
            },
        ),
    ]
