# Generated by Django 6.0.3 on 2026-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0002_alter_security_interest_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='cash',
            new_name='cash_balance',
        ),
        migrations.AddField(
            model_name='security',
            name='current_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='holding',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
