# Generated by Django 6.0.3 on 2026-03-11 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='recurrence_period',
        ),
        migrations.RemoveField(
            model_name='income',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='income',
            name='recurrence_period',
        ),
        migrations.AddField(
            model_name='category',
            name='is_preset',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
        migrations.DeleteModel(
            name='BudgetPeriod',
        ),
    ]
