# Generated by Django 6.0.3 on 2026-03-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_remove_expense_is_recurring_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='notes',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
