# Generated by Django 6.0.3 on 2026-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_notes_income_description_alter_income_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
