# Generated by Django 6.0.3 on 2026-04-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_remove_income_source_income_notes_and_more'),
        ('vault', '0004_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.account'),
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vault.account'),
        ),
    ]
