# Generated by Django 6.0.3 on 2026-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('cash', 'Physical Cash'), ('credit_card', 'Credit Card'), ('loan', 'Personal/Auto Loan'), ('mortgage', 'Mortgage')], max_length=20),
        ),
    ]
