# Generated by Django 6.0.3 on 2026-03-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_invest_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides risk tolerance suggestion. Leave blank to use default.', max_digits=5, null=True),
        ),
    ]
