# Generated by Django 6.0.3 on 2026-03-17 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_custom_invest_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='default_invest_percentage',
        ),
    ]
