# Generated by Django 6.0.3 on 2026-03-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
