# Generated by Django 6.0.3 on 2026-03-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
